version: "3.7"

services:
  ukulele:
    image: ukulele #TODO: Change to real Image before merging
    restart: always
    environment:
      CONFIG_DATABASE: ./db/database # Database location overwrite so mounting works
    volumes:
      - ./ukulele.yml:/opt/ukulele/ukulele.yml
      - ./db:/opt/ukulele/db